services:
  server:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=dev
    ports: 
      - "8080:8080"
    command: "npm run dev"
    develop:
      watch:
        - action: rebuild
          path: ./backend/package.json
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore: 
            - node_modules

  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'mydatabase'
    volumes:
      - C:/docker/postgres-data:/var/lib/postgresql/data

  prisma-studio:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=dev
    ports: 
      - "5555:5555"
    develop:
      watch:
        - action: rebuild
          path: ./backend/graphql
    command: "npx prisma studio"
    volumes:
      - D:/coding/ksports/backend/src/generated/client:/app/src/generated/client

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "dev"
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore: 
            - node_modules