version: '3.9'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        PROD_ENV: "false" 
    ports: 
      - "8080:8080"
    depends_on:
      - db
    command: ["node dist/index.js"]

  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'mydatabase'

  prisma-studio:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        PROD_ENV: "false" 
    ports: 
      - "5555:5555"
    depends_on:
      - db
    command: ["npx prisma migrate dev --name new1 && npx prisma studio"]
