name: Build and Deploy to Azure

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZ_CREDENTIALS }}'

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZR_LOGIN_SERVER }}
        username: ${{ secrets.AZR_LOGIN_USERNAME }}
        password: ${{ secrets.AZR_LOGIN_PASSWORD }}


    - name: Build and push Docker image
      run: |
        docker build -t klintregistry.azurecr.io/ksportsbackend:1.0 ./backend
        docker push klintregistry.azurecr.io/ksportsbackend:1.0

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ksportsbackend # Replace with your App Service name
        images: 'klintregistry.azurecr.io/ksportsbackend:1.0'
        slot-name: production # Optional, specify the slot name if you are using deployment slots
